server:
    port: 8191
spring:
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/pasindu-sandaruwan/spring-cloud-config-store
                    search-paths:
                        - "*service"
    datasource:
      url: jdbc:mysql://localhost:3306/sample?createDatabaseIfNotExist=true
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
